### ISSUE TITLE
Error Installing Plug-in (QGIS 3.12.0; Python 3.8.2)

### ISSUE THREAD

**Issue by canunen** [thangqd/HCMGIS#10]
I have updated the plugin, but got an error. The updated plugin gives the following error report and doesn't load. 

Operating System: Manjaro Linux, Kernel 5.4.34-1

Couldn't load plugin 'HCMGIS' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'hcmgis_library' 
Traceback (most recent call last):
  File "/home/can/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/hcmgis_dialogs.py", line 32, in 
    from .hcmgis_library import *
  File "/usr/lib/python3.8/site-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/can/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/hcmgis_library.py", line 14, in 
    import xlrd
  File "/usr/lib/python3.8/site-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'xlrd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/can/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/__init__.py", line 11, in classFactory
    from .hcmgis_menu import hcmgis_menu
  File "/usr/lib/python3.8/site-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/can/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/hcmgis_menu.py", line 11, in 
    from .hcmgis_dialogs import *
  File "/usr/lib/python3.8/site-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/can/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/hcmgis_dialogs.py", line 34, in 
    from hcmgis_library import *
  File "/usr/lib/python3.8/site-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'hcmgis_library'

Python version: 3.8.2 (default, Apr  8 2020, 14:31:25) [GCC 9.3.0] 
QGIS version: 3.12.0-București București, exported 

Python Path:
/usr/share/qgis/python
/home/can/.local/share/QGIS/QGIS3/profiles/default/python
/home/can/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/usr/lib/python3.8/site-packages
/home/can/.local/share/QGIS/QGIS3/profiles/default/python

**Comment by LeonDBL** [comment]
Can second the above. Manjaro on the 5.6 kernel with Q 3.12. Exactly the same issue. I've tried installing from zip using the master branch from Github too...but same issue again.

**Comment by Doctor-Who** [comment]
Same issue with openSUSE Leap 15.1 

Version de Python : 3.6.10 (default, Jan 16 2020, 09:12:04) [GCC] 
Version de QGIS : 3.12.1-București București, exported

**Comment by thangqd** [comment]
Please try:
`pip install xlrd`
And let me know for further problems
Thanks

**Comment by thangqd** [comment]
And please update HCMGIS to Version 20.5.4 which fixing some bugs in MacOS. Thanks

**Comment by Doctor-Who** [comment]
@thangqd Thanks for quick answering.
In my case, installing xlrd and update to latest 20.5.4 work for me :) 
I've also test on a clean VM by installating xlrd and the plugin : works too.

**Comment by LeonDBL** [comment]
Can also confirm this fix worked for me too. Thank you.

**Comment by Tiagojsf** [comment]
@thangqd I am having the same issue with QGIS 3.10 in Ubuntu 18.04. Tried the solution 'pip install xlrd' but the problem remains.

Python version: 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0] 
QGIS version: 3.10.5-A Coruña A Coruña, 984615fe1e 

Thanks in advance!

**Comment by thangqd** [comment]
@Tiagojsf  please attach a screenshot or error log. HCMGIS Plugin works fine on my Ubuntu (Virtual Box)
![image](https://user-images.githubusercontent.com/1776420/81151558-4fd8a880-8fab-11ea-9d53-19de089fa982.png)

**Comment by canunen** [comment]
> Please try:
> `pip install xlrd`
> And let me know for further problems
> Thanks

Worked for me as well. Thanks a lot.

**Comment by PedroVenancio** [comment]
Hi @thangqd 

`xlrd` really fix this issue. Thanks!

Besides pip, `xlrd` is present in OSGeo4W and Ubuntu repositories, so I think you should mention in the plugin description that `xlrd` is a requirement.

**Comment by Doctor-Who** [comment]
Will it be possible to directly include it in the plugin ?
For non root user that can't install packages

**Comment by thangqd** [comment]
Please update to version HCMGIS ver 20.6.3, with no 'pip install xlrd' requirement anymore. Thanks
[http://plugins.qgis.org/plugins/HCMGIS/](url)

**Comment by Doctor-Who** [comment]
Great job, thanks
