### ISSUE TITLE
Global Administraive Areas by Country doesn't work anymore

### ISSUE THREAD

**Issue by itsyurig** [thangqd/HCMGIS#14]
Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 

any help with this? is this just a server problem that will be fixed soon?

**Comment by thangqd** [comment]
> Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
> 
> any help with this? is this just a server problem that will be fixed soon?

Hi @itsyurig 
I have checked and it works find, please recheck and post your error screenshot for any further issue
