### ISSUE TITLE
Error Message by converting shp into gpkg on QGIS desktop 3.34.8 LTR with HCMGIS

### ISSUE THREAD

**Issue by mcorthay** [thangqd/HCMGIS#19]
Dear Qgis-developpers,

I tried to convert a layer from shp to gpkg on QGIS desktop 3.34.8 LTR with HCMGIS and I got following error message :

[ TypeError: setValue(self, value: int): argument 1 has unexpected type 'float' 
Traceback (most recent call last):
  File "C:\Users/mathiasc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HCMGIS\hcmgis_dialogs.py", line 2486, in run
    self.status_bar.setValue(percent_complete)
TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'

Version de Python : 3.12.4 (main, Jun 10 2024, 12:48:35) [MSC v.1938 64 bit (AMD64)] 
Version de QGIS : 3.34.8-Prizren Prizren, 91642333 
Chemin Python :
•	C:/PROGRA~1/QGIS33~1.8/apps/qgis-ltr/./python
•	C:/Users/mathiasc/AppData/Roaming/QGIS/QGIS3\profiles\default/python
•	C:/Users/mathiasc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
•	C:/PROGRA~1/QGIS33~1.8/apps/qgis-ltr/./python/plugins
•	C:\PROGRA~1\QGIS33~1.8\apps\grass\grass83\etc\python
•	C:\Users\mathiasc\Documents
•	C:\Program Files\QGIS 3.34.8\bin\python312.zip
•	C:\PROGRA~1\QGIS33~1.8\apps\Python312\DLLs
•	C:\PROGRA~1\QGIS33~1.8\apps\Python312\Lib
•	C:\Program Files\QGIS 3.34.8\bin
•	C:\PROGRA~1\QGIS33~1.8\apps\Python312
•	C:\PROGRA~1\QGIS33~1.8\apps\Python312\Lib\site-packages
•	C:\PROGRA~1\QGIS33~1.8\apps\Python312\Lib\site-packages\win32
•	C:\PROGRA~1\QGIS33~1.8\apps\Python312\Lib\site-packages\win32\lib
•	C:\PROGRA~1\QGIS33~1.8\apps\Python312\Lib\site-packages\Pythonwin
•	C:/Users/mathiasc/AppData/Roaming/QGIS/QGIS3\profiles\default/python
•	C:\Users\mathiasc\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
•	C:\Users\mathiasc\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qfieldsync\libqfieldsync.whl
C:/Users/mathiasc/_QGIS ]

I did not understand the content of this message. So I tried same with QGIS 3.22.16 and it worked. So I deinstalled QGIS 3.34.8 LTR and installed it again for the same result. 

Best regards

Mathias Corthay

**Comment by thangqd** [comment]
Fixed. Thank you @mcorthay
