### ISSUE TITLE
Float type error Vector Format Batch Converter

### ISSUE THREAD

**Issue by udaf-mcq** [thangqd/HCMGIS#20]
Attempting to convert Geojson file to shape file.
Geojson file was from CSV to Point program.  The original CSV file was 4 columns.  1- Id integer number, 2- longitude in decimal format with - for west longitude (-111.xxx), 3- latitude decimal degree format, 4- elevation in meters, all columns separted by ",".
![Geojson-to-Shape](https://github.com/user-attachments/assets/ed9aff3f-c673-49df-b1fa-32ff26b0cb25)

Here is the error message:
TypeError: setValue(self, value: int): argument 1 has unexpected type 'float' 
Traceback (most recent call last):
  File "C:\Users/mquilter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HCMGIS\hcmgis_dialogs.py", line 2486, in run
    self.status_bar.setValue(percent_complete)
TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'

Python version: 3.12.7 (main, Oct 25 2024, 11:
![Geojson-to-Shape](https://github.com/user-attachments/assets/2051b731-62ba-4fc2-a023-5e0c51893dc2)
18:09) [MSC v.1938 64 bit (AMD64)] 
QGIS version: 3.34.12-Prizren Prizren, eeb6af3638 

Python Path:
C:\Users/mquilter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lftools
C:\Users/mquilter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools
C:\Users/mquilter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geomelwatershed-master
C:\Users/mquilter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\contour
C:\Users/mquilter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\clusterpoints
C:/OSGeo4W/apps/qgis-ltr/./python
C:/Users/mquilter/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/mquilter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis-ltr/./python/plugins
C:\OSGeo4W\apps\grass\grass84\etc\python
C:\Users\mquilter\Documents
C:\OSGeo4W\bin\python312.zip
C:\OSGeo4W\apps\Python312\DLLs
C:\OSGeo4W\apps\Python312\Lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python312
C:\OSGeo4W\apps\Python312\Lib\site-packages
C:\OSGeo4W\apps\Python312\Lib\site-packages\win32
C:\OSGeo4W\apps\Python312\Lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/mquilter/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\mquilter\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\deepness\python3.12
C:\Users\mquilter\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\mquilter\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:\Users\mquilter\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs
C:\Users/mquilter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geomelwatershed-master\main
C:\Users/mquilter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geomelwatershed-master\sub
C:\Users\mquilter\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
C:\Users\mquilter\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\kmltools\libs
C:\Users\mquilter\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
.
C:\Users/mquilter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rvt-qgis
C:\Users/mquilter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tree_eyed\dependencies
C:\Users\mquilter\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
F:/
C:\Users\mquilter\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms

**Comment by thangqd** [comment]
Thanks @udaf-mcq. Please upgrade to HCMGIS 24.11.20 (latest version)
