### ISSUE TITLE
Batch Convert CSV to Point Not Working

### ISSUE THREAD

**Issue by udaf-mcq** [thangqd/HCMGIS#21]
I have a CSV file with ID, Latitude, Longitude, Elevation.  Using the QGIS plugin HCMGIS Batch Convert CSV to Point I get the following error:  "Unsupported output".  I have been doing this with several data sets without a problem in previous days.  All of these data sets were produced using the same procedures and appear the same (excepting values have changed).

What causes the "Unsupported output" error?  Have attached one of the files that will not convert.
[MAX_0659.CSV](https://github.com/user-attachments/files/18156127/MAX_0659.CSV)

**Comment by thangqd** [comment]
Hi @udaf-mcq 
This issue has been fixed and will be released in the next version (coming soon). Meanwhile, you can rename your CSV extension  to lowercase, something like *.csv, then it works!
Thanks for your report
Regards!

**Comment by udaf-mcq** [comment]
Thanks, I will try it with lower case.
