### ISSUE TITLE
Please consider bringing your work upstream

### ISSUE THREAD

**Issue by pcav** [thangqd/HCMGIS#3]
Hi,
I find many functions of your plugin simply amazing, and of very general use. I'd be more than happy of helping bringing the general functions in main QGIS. Analytical functions could go to Processing, base map should really be standard if licence allows. Please consider this possibility and let us know.
Thanks.

**Comment by thangqd** [comment]
Dear Dr. Paolo Cavallini!
It's my honor to receive recommendations from you.
- As you can see in the source code, most of HCMGIS Processing functions (Centerline, closest pair of Point, LEC, ect) are just a series of core functions from QGIS Processing (similar to QGIS Processing Modeler).
- All the basemaps (XYZ Tiling) in HCMGIS Plugin are freely used without any API Key requirements from map service providers
I'm very happy to hear that HCMGIS Plugin could contribute to the core functions of QGIS
I'm very excited and willing to cooperate with the core team of QGIS to make this come true
Hearing from you for further information and guidance!
Best regards!

**Comment by pcav** [comment]
I didn't check the code (sorry, not enough time). Are you sure it is good to duplicate code? Couldn't you just call the underlying Processing alg?
As for the tiles, it would be good if you could find a way to add them as a default. Currently the functionality is not much used because of that.

**Comment by thangqd** [comment]
Dear Dr. Paolo Cavallini!
Let me clarify more about HCMGIS Plugin:
- For the Skeleton, Centerline, Closest Pair of Points, Largest Empty Circle Functions: They are based on "Applying Voronoi Diagram in solving computational geometry problems". 
Each alg is a process including some functions to solve a practical problem. 
For example, the Skeleton/ Medial Axis function of HCMGIS used these core algs of QGIS: saveselectedfeatures -> polygonstolines -> pointsalonglines -> voronoipolygons -> polygonstolines -> explodelines -> selectbylocation -> saveselectedfeatures -> deleteduplicategeometries -> dissolve -> simplifygeometries
In my opinion, I don't duplicate the code (I don't simply turn the core algs into my own alg!). On the other hand, I don't think reinvent the wheel is a good approach for a developer.  So reuse core algs to create a new alg is my favourite choice to save time.
- For other functions such as add Basemap, Download HCMGIS Opendata, Merge/ Split field, Vietnamese Font Converter: using my own code and alg
- For the basemap: I don't understand  clearly what you mean about "adding basemap as a default" . I just organize dozens of basemaps for users to choose depending on their needs
Thanks and best regards!

**Comment by pcav** [comment]
Thanks for clarifying. So:
* the new algs you created as a combination of existing tools could be even more useful if added to main Processing
* other functions developed by you would be very useful as well
* in my opinion it would be good if the base maps you added to your plugin would be added to the standard QGIS installation, so the user will find them straight away. Could you please have a look and check whether this is feasible for you?
Thanks again.

**Comment by thangqd** [comment]
Dear Dr. Paolo Cavallini!
Great to hear that HCMGIS Plugin would contribute to the QGIS core functions.
I appreciate your recommendations and I'm really ready to share my works with QGIS Developer Team. Please instruct me for further steps
Thank you and best regards!

**Comment by pcav** [comment]
Could you please have a look to the XYZ implementation in QGIS core and see if you are able to add some default base layers? Of course this should be discussed both with the map providers, because of the heavy load we could impose on them, and with QGIS core team, for possible issues.
Thanks!

**Comment by thangqd** [comment]
Dear Dr. Paolo Cavallini!
I'm going to contact with QGIS core team to add XYZ basemaps into QGIS as default. It's no problem to add basemaps because we just simply add some URL address to QGIS and the basemap will be loaded when users call it. Beside that, XYZ tiling is really fast and smooth due to the fact that it is tiled and cached into tiles before rendering at client side.
Thank you and best regards!

**Comment by pcav** [comment]
Thanks!
